package change

import (
	"strings"
	"testing"
)

const translationDivider = "<!--This is a translation content dividing line, the content below is generated by machine, please do not modify the content below-->"

func translatedIssueBody(original string) string {
	return original + "\n\n" + translationDivider + "\n\n" + original
}

func TestParseMarkerToleratesTranslatedIssueBodies(t *testing.T) {
	original := "<!-- issue-spec:issue=proposal change=widget version=1 -->\n# Proposal: widget\n\n- Design Issue: 12\n"
	tests := []struct {
		name    string
		body    string
		wantErr string
	}{
		{name: "translated body", body: translatedIssueBody(original)},
		{name: "degraded marker copy in suffix", body: original + "\n\n" + translationDivider + "\n\n<!--issue-spec:issue=proposal change=widget version=1-->\n# PROPOSAL\n"},
		{name: "genuine duplicate marker still fails", body: original + "<!-- issue-spec:issue=proposal change=other version=1 -->\n", wantErr: "exactly once"},
		{name: "unclosed fence in original fails closed", body: "```\n" + translatedIssueBody(original), wantErr: "exactly once"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			kind, key, err := parseMarker(test.body)
			if test.wantErr == "" {
				if err != nil || kind != "proposal" || key != "widget" {
					t.Fatalf("parseMarker = %q %q %v, want proposal widget", kind, key, err)
				}
				return
			}
			if err == nil || !strings.Contains(err.Error(), test.wantErr) {
				t.Fatalf("parseMarker error = %v, want %q", err, test.wantErr)
			}
		})
	}
}

func TestExactPredecessorToleratesTranslatedIssueBodies(t *testing.T) {
	implement := "<!-- issue-spec:issue=implement change=widget version=1 -->\n# Implement\n\n- Design Issue: 12\n"
	if number, err := exactPredecessor(translatedIssueBody(implement), designIssue, "Design Issue"); err != nil || number != 12 {
		t.Fatalf("exactPredecessor = %d %v, want 12", number, err)
	}
	design := "<!-- issue-spec:issue=design change=widget version=1 -->\n# Design\n\n- Proposal Issue: 7\n"
	if number, err := exactPredecessor(translatedIssueBody(design), proposalIssue, "Proposal Issue"); err != nil || number != 7 {
		t.Fatalf("exactPredecessor = %d %v, want 7", number, err)
	}
	genuine := implement + "- Design Issue: 99\n"
	if _, err := exactPredecessor(genuine, designIssue, "Design Issue"); err == nil || !strings.Contains(err.Error(), "exactly once") {
		t.Fatalf("genuine duplicate predecessor error = %v", err)
	}
}
