package commands

import (
	"context"
	"strings"
	"testing"

	"github.com/higress-group/issue-spec/internal/github"
)

const issueTranslationDivider = "<!--This is a translation content dividing line, the content below is generated by machine, please do not modify the content below-->"

func TestValidatePhasePredecessorToleratesTranslatedIssueBodies(t *testing.T) {
	original := "<!-- issue-spec:issue=proposal change=predecessor-tolerance version=1 -->\n# Proposal\n\nBody.\n"
	translated := original + "\n\n" + issueTranslationDivider + "\n\n" + original
	client := fakeGitHubBackend{getIssue: func(_ context.Context, _ string, issueNumber int) (github.Issue, error) {
		return github.Issue{Number: issueNumber, Body: translated}, nil
	}}
	if err := validatePhasePredecessor(context.Background(), client, "o/r", 21, "proposal", "predecessor-tolerance"); err != nil {
		t.Fatalf("translated proposal rejected: %v", err)
	}
}

func TestValidatePhasePredecessorStillFailsClosed(t *testing.T) {
	original := "<!-- issue-spec:issue=proposal change=predecessor-tolerance version=1 -->\n# Proposal\n"
	tests := []struct {
		name    string
		body    string
		wantErr string
	}{
		{name: "genuine duplicate marker", body: original + "<!-- issue-spec:issue=design change=other version=1 -->\n", wantErr: "exactly one"},
		{name: "unclosed fence in original plus suffix", body: "```\n" + original + "\n\n" + issueTranslationDivider + "\n\n" + original, wantErr: "exactly one"},
		{name: "wrong change", body: "<!-- issue-spec:issue=proposal change=another-change version=1 -->\n# Proposal\n", wantErr: "belongs to change"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			client := fakeGitHubBackend{getIssue: func(_ context.Context, _ string, issueNumber int) (github.Issue, error) {
				return github.Issue{Number: issueNumber, Body: test.body}, nil
			}}
			err := validatePhasePredecessor(context.Background(), client, "o/r", 21, "proposal", "predecessor-tolerance")
			if err == nil || !strings.Contains(err.Error(), test.wantErr) {
				t.Fatalf("error = %v, want %q", err, test.wantErr)
			}
		})
	}
}
