package commands

import (
	"strings"
	"testing"
)

const projectionTranslationDivider = "<!--This is a translation content dividing line, the content below is generated by machine, please do not modify the content below-->"

func TestParseProjectionMarkersToleratesTranslatedBody(t *testing.T) {
	digest := strings.Repeat("a", 64)
	body := "<!-- issue-spec:projection phase=design-explainer owner=1 version=1 source-digest=" + digest + " -->\n\n# Projection\n\nContent.\n"
	translated := body + "\n\n" + projectionTranslationDivider + "\n\n" + body

	markers, err := parseProjectionMarkers(translated)
	if err != nil {
		t.Fatalf("translated projection body rejected: %v", err)
	}
	if len(markers) != 1 || markers[0].Phase != "design-explainer" || markers[0].Owner != 1 ||
		markers[0].SourceDigest != digest {
		t.Fatalf("markers=%+v", markers)
	}
	plain, err := parseProjectionMarkers(body)
	if err != nil || len(plain) != 1 || plain[0] != markers[0] {
		t.Fatalf("plain markers=%+v err=%v", plain, err)
	}

	// Genuine duplicates outside a recognized suffix stay surfaced so the
	// unique-projection caller still reports the ambiguity.
	genuine := body + "<!-- issue-spec:projection phase=implement-execution-brief owner=2 version=1 source-digest=" +
		strings.Repeat("b", 64) + " -->\n"
	duplicates, err := parseProjectionMarkers(genuine)
	if err != nil || len(duplicates) != 2 {
		t.Fatalf("genuine duplicates markers=%+v err=%v", duplicates, err)
	}
}
