package relationships

import (
	"errors"
	"strings"
	"testing"

	"github.com/higress-group/issue-spec/internal/model"
)

const mutationTranslationDivider = "<!--This is a translation content dividing line, the content below is generated by machine, please do not modify the content below-->"

func TestApplyMutationIgnoresSemanticMatchesInTranslatedSuffix(t *testing.T) {
	spec := relationshipArtifact(t, 1, "SPEC", "SPEC-001", "## Specification", nil)
	task := relationshipArtifact(t, 3, "TASK", "TASK-001",
		"## Task\n\n### Covers\n\n- SPEC-001\n\ncontent stays", []string{spec.URL})
	rawBody := task.Comment.Body + "\n\n" + mutationTranslationDivider + "\n\n" + strings.ToUpper(task.Comment.Body)
	observed := model.Artifact{Issue: task.Issue, URL: task.URL, APIURL: task.APIURL,
		Comment: model.ParseTypedComment(rawBody)}
	owner, target := mustRef(t, task), mustRef(t, spec)
	frozen, err := PlanMutation([]model.Artifact{spec, observed}, owner, nil, []model.ArtifactRef{target},
		rawBody, 3, DefaultMutationTargetLimit)
	if err != nil {
		t.Fatalf("translated owner broke mutation planning: %v", err)
	}
	if !strings.Contains(frozen.DesiredBody, mutationTranslationDivider) {
		t.Fatalf("provider suffix must survive the mutation:\n%s", frozen.DesiredBody)
	}
	if strings.Count(frozen.DesiredBody, "- SPEC-001") != 1 {
		t.Fatalf("suffix bullet must not be mutated, prefix bullet must be removed:\n%s", frozen.DesiredBody)
	}
}

func TestApplyMutationStillFailsOnWithinPrefixDuplicates(t *testing.T) {
	spec := relationshipArtifact(t, 1, "SPEC", "SPEC-001", "## Specification", nil)
	task := relationshipArtifact(t, 3, "TASK", "TASK-001", "## Task\n\n### Covers\n\n- SPEC-001\n- SPEC-001",
		[]string{spec.URL})
	owner, target := mustRef(t, task), mustRef(t, spec)
	_, err := PlanMutation([]model.Artifact{spec, task}, owner, nil, []model.ArtifactRef{target},
		task.Comment.Body, 1, DefaultMutationTargetLimit)
	if !errors.Is(err, ErrAmbiguous) || !strings.Contains(err.Error(), "duplicated") {
		t.Fatalf("within-prefix duplicate error = %v", err)
	}
}

func TestApplyMutationFailsClosedWhenHeadingExistsOnlyInSuffix(t *testing.T) {
	spec := relationshipArtifact(t, 1, "SPEC", "SPEC-001", "## Specification", nil)
	task := relationshipArtifact(t, 3, "TASK", "TASK-001", "## Task\n\ncontent only", []string{spec.URL})
	body := task.Comment.Body + "\n\n" + mutationTranslationDivider + "\n\n## Task\n\n### Covers\n\n- SPEC-001\n"
	owner, target := mustRef(t, task), mustRef(t, spec)
	_, err := PlanMutation([]model.Artifact{spec, task}, owner, nil, []model.ArtifactRef{target},
		body, 1, DefaultMutationTargetLimit)
	if err == nil || errors.Is(err, ErrAmbiguous) {
		t.Fatalf("suffix-only heading must fail closed without ambiguity, got %v", err)
	}
}
