package model

import (
	"strings"
)

// translationDivider is the single recognized machine-translation divider
// emitted by the lizheming/github-translate-action workflow. The allowlist is
// deliberately exactly one byte-exact literal; any other divider wording means
// no strip and the raw body keeps today's parsing behavior.
const translationDivider = "<!--This is a translation content dividing line, the content below is generated by machine, please do not modify the content below-->"

// StripTranslationSuffix removes a recognized machine-translation suffix: the
// divider line and everything after it. The suffix qualifies only when the
// divider is a standalone line (optional surrounding whitespace) outside
// ``` / ~~~ / html-preview fences, and exactly one qualifying divider exists
// in the whole raw body; two dividers mean a human quoted the literal and no
// strip applies. The result is the strip-only canonical view: no preview
// masking and no other normalization beyond collapsing the trailing blank
// lines the suffix join introduced. Bodies without a recognized suffix are
// returned byte-identical with stripped=false.
func StripTranslationSuffix(body string) (string, bool) {
	lines := strings.Split(body, "\n")
	qualifying := qualifyingDividerLines(lines)
	if len(qualifying) != 1 {
		return body, false
	}
	prefix := strings.Join(lines[:qualifying[0]], "\n")
	trimmed := strings.TrimRight(prefix, "\r\n")
	if trimmed == "" {
		return "", true
	}
	return trimmed + "\n", true
}

// CanonicalView returns the strip-only canonical view of body. It applies
// translation-suffix stripping only: no preview masking and no other
// normalization. Consumers that interpret issue-spec syntax inside preview
// sources additionally apply preview.SemanticView to this view.
func CanonicalView(body string) string {
	canonical, _ := StripTranslationSuffix(body)
	return canonical
}

// CanonicalBodyEqual reports whether two bodies carry the same canonical
// content. Trailing newline runs are insignificant: a provider body observed
// after issue-spec's own write differs from the written body only by the
// translation suffix (and its join bytes), never by semantic content.
func CanonicalBodyEqual(left, right string) bool {
	return strings.TrimRight(CanonicalView(left), "\r\n") == strings.TrimRight(CanonicalView(right), "\r\n")
}

// TranslationDividerLine returns the zero-based raw line index of the single
// qualifying translation divider, or -1 when no strip applies. Write-path
// scans use it as an exclusive bound so matches in a translated suffix are
// never considered while raw-line index arithmetic stays untouched.
func TranslationDividerLine(body string) int {
	qualifying := qualifyingDividerLines(strings.Split(body, "\n"))
	if len(qualifying) != 1 {
		return -1
	}
	return qualifying[0]
}

// CanonicalTitle strips a machine-translation title suffix (` || <English>`)
// for equality and lookup comparisons only. Display keeps the full title;
// titles are not canonical carriers.
func CanonicalTitle(title string) string {
	index := strings.LastIndex(title, " || ")
	if index < 0 {
		return title
	}
	return strings.TrimSpace(title[:index])
}

// qualifyingDividerLines returns the raw line indexes of divider lines that
// pass the allowlist and fence guard. Fence tracking mirrors preview.Parse:
// a fence opener consumes lines until an exact closer, and an unclosed fence
// swallows the remainder of the body, so a divider after it never qualifies.
func qualifyingDividerLines(lines []string) []int {
	var qualifying []int
	inFence := false
	var fenceChar byte
	fenceLength := 0
	for index, raw := range lines {
		content := strings.TrimSuffix(raw, "\r")
		if inFence {
			if isFenceCloser(content, fenceChar, fenceLength) {
				inFence = false
			}
			continue
		}
		if strings.TrimSpace(content) == translationDivider {
			qualifying = append(qualifying, index)
			continue
		}
		if char, length, ok := isFenceOpener(content); ok {
			inFence = true
			fenceChar = char
			fenceLength = length
		}
	}
	return qualifying
}

// isFenceOpener mirrors preview fence-opener recognition: up to three leading
// spaces, a run of at least three ` or ~ characters, and no backtick in the
// info string of a backtick fence.
func isFenceOpener(content string) (byte, int, bool) {
	index := 0
	for index < len(content) && content[index] == ' ' && index < 4 {
		index++
	}
	if index > 3 || index >= len(content) || (content[index] != '`' && content[index] != '~') {
		return 0, 0, false
	}
	char := content[index]
	runEnd := index
	for runEnd < len(content) && content[runEnd] == char {
		runEnd++
	}
	if runEnd-index < 3 {
		return 0, 0, false
	}
	if char == '`' && strings.Contains(content[runEnd:], "`") {
		return 0, 0, false
	}
	return char, runEnd - index, true
}

// isFenceCloser mirrors preview fence-closer recognition: the same fence
// character, a run at least as long as the opener, and only spaces or tabs
// after the run.
func isFenceCloser(content string, char byte, minimum int) bool {
	index := 0
	for index < len(content) && content[index] == ' ' && index < 4 {
		index++
	}
	if index > 3 || index >= len(content) || content[index] != char {
		return false
	}
	runEnd := index
	for runEnd < len(content) && content[runEnd] == char {
		runEnd++
	}
	if runEnd-index < minimum {
		return false
	}
	for _, value := range content[runEnd:] {
		if value != ' ' && value != '\t' {
			return false
		}
	}
	return true
}
