package model

import (
	"strings"
	"testing"
)

const testTranslationDivider = "<!--This is a translation content dividing line, the content below is generated by machine, please do not modify the content below-->"

func suffixedBody(original, translation string) string {
	return original + "\n\n" + testTranslationDivider + "\n\n" + translation
}

func TestStripTranslationSuffix(t *testing.T) {
	original := "<!-- issue-spec:type=SPEC id=SPEC-001 version=1 -->\nAgent: Coordinator\nType: SPEC\nID: SPEC-001\nStatus: confirmed\nScope: N/A\n\n## Requirement: Beta\n\nThe system MUST work.\n"
	machineCopy := "<!-- issue-spec:type=SPEC id=SPEC-001 version=1 -->\nAgent: Coordinator\nType: SPEC\nID: SPEC-001\nStatus: confirmed\n\n## Requirement: Alpha\n\nThe system MUST work.\n"
	tests := []struct {
		name      string
		body      string
		want      string
		stripped  bool
		idempoten bool
	}{
		{name: "no suffix is passthrough", body: original, want: original, stripped: false},
		{name: "suffix duplicating marker and sections is stripped", body: suffixedBody(original, machineCopy), want: original, stripped: true},
		{name: "re-translated suffix is stripped", body: suffixedBody(original, strings.ToUpper(machineCopy)), want: original, stripped: true},
		{name: "divider with surrounding whitespace", body: original + "\n\n  \t" + testTranslationDivider + "  \n\ntranslated", want: original, stripped: true},
		{name: "unknown divider wording is kept", body: original + "\n\n<!--some other dividing line do not edit below-->\n\n" + machineCopy, want: original + "\n\n<!--some other dividing line do not edit below-->\n\n" + machineCopy, stripped: false},
		{name: "divider inside backtick fence is kept", body: "```text\n" + testTranslationDivider + "\n```\n" + original, want: "```text\n" + testTranslationDivider + "\n```\n" + original, stripped: false},
		{name: "divider inside tilde fence is kept", body: original + "\n\n~~~\n" + testTranslationDivider + "\n~~~\n", want: original + "\n\n~~~\n" + testTranslationDivider + "\n~~~\n", stripped: false},
		{name: "divider inside html-preview fence is kept", body: original + "\n\n```html-preview id=growth\n" + testTranslationDivider + "\n```\n", want: original + "\n\n```html-preview id=growth\n" + testTranslationDivider + "\n```\n", stripped: false},
		{name: "unclosed fence swallows divider", body: "```\nunclosed\n" + suffixedBody(original, machineCopy), want: "```\nunclosed\n" + suffixedBody(original, machineCopy), stripped: false},
		{name: "two qualifying dividers do not strip", body: original + "\n\n" + testTranslationDivider + "\n\nquoted by a human\n\n" + testTranslationDivider + "\n\n" + machineCopy, want: original + "\n\n" + testTranslationDivider + "\n\nquoted by a human\n\n" + testTranslationDivider + "\n\n" + machineCopy, stripped: false},
		{name: "lone human-authored divider is stripped", body: original + "\n\n" + testTranslationDivider + "\n\ndocumenting the bot convention", want: original, stripped: true},
		{name: "fenced divider does not count toward single-divider rule", body: "```text\n" + testTranslationDivider + "\n```\n" + suffixedBody(original, machineCopy), want: "```text\n" + testTranslationDivider + "\n```\n" + original, stripped: true},
		{name: "divider only body strips to empty", body: testTranslationDivider + "\n\n" + machineCopy, want: "", stripped: true},
		{name: "empty body", body: "", want: "", stripped: false},
		{name: "crlf body without suffix is passthrough", body: "Agent: Coordinator\r\nType: SPEC\r\n", want: "Agent: Coordinator\r\nType: SPEC\r\n", stripped: false},
		{name: "crlf body with suffix", body: "Agent: Coordinator\r\n\r\n" + testTranslationDivider + "\r\n\r\ntranslated", want: "Agent: Coordinator\n", stripped: true},
		{name: "divider mid-body only strips tail", body: "head line\n\n" + testTranslationDivider + "\n\ntail", want: "head line\n", stripped: true},
		{name: "blockquoted divider does not qualify", body: original + "\n\n> " + testTranslationDivider + "\n\nquoted", want: original + "\n\n> " + testTranslationDivider + "\n\nquoted", stripped: false},
		{name: "mixed fence chars leave fence unclosed", body: original + "\n\n```\ncode\n~~~\n\n" + testTranslationDivider + "\n\ncopy", want: original + "\n\n```\ncode\n~~~\n\n" + testTranslationDivider + "\n\ncopy", stripped: false},
		{name: "divider as last line without trailing newline still strips", body: original + "\n\n" + testTranslationDivider, want: original, stripped: true},
		{name: "four-space indented divider qualifies by design", body: original + "\n\n    " + testTranslationDivider + "  \n\ncopy", want: original, stripped: true},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			got, stripped := StripTranslationSuffix(test.body)
			if stripped != test.stripped {
				t.Fatalf("stripped = %v, want %v", stripped, test.stripped)
			}
			if got != test.want {
				t.Fatalf("StripTranslationSuffix = %q, want %q", got, test.want)
			}
			if again := CanonicalView(got); again != got {
				t.Fatalf("CanonicalView not idempotent: %q then %q", got, again)
			}
		})
	}
}

func TestCanonicalViewMatchesStripOnly(t *testing.T) {
	body := suffixedBody("content\n", "copy")
	stripped, ok := StripTranslationSuffix(body)
	if !ok || CanonicalView(body) != stripped {
		t.Fatalf("CanonicalView must equal the strip-only view: %q vs %q", CanonicalView(body), stripped)
	}
}

func TestRepresentationDigestStabilityBoundaryOnTrailingNewlines(t *testing.T) {
	oneLF := "## Requirement\n\nThe system MUST work.\n"
	suffix := "\n\n" + testTranslationDivider + "\n\nmachine copy"
	if RepresentationDigest(oneLF) != RepresentationDigest(oneLF+suffix) {
		t.Fatal("original ending in exactly one LF must keep its digest across a suffix")
	}
	noLF := strings.TrimRight(oneLF, "\n")
	if RepresentationDigest(noLF) == RepresentationDigest(noLF+suffix) {
		t.Fatal("original with zero trailing LF must fail closed: digest changed by the suffix")
	}
	twoLF := oneLF + "\n"
	if RepresentationDigest(twoLF) == RepresentationDigest(twoLF+suffix) {
		t.Fatal("original with two trailing LFs must fail closed: digest changed by the suffix")
	}
	stripped, ok := StripTranslationSuffix(noLF + suffix)
	if !ok || stripped != oneLF {
		t.Fatalf("strip canonicalizes to the single-LF form: stripped=%q ok=%v", stripped, ok)
	}
}

func TestCanonicalViewWithoutDividerIsAllocationFree(t *testing.T) {
	body := strings.Repeat("ordinary provider text line\n", 256)
	if strings.Contains(body, testTranslationDivider) {
		t.Fatal("fixture must not contain the divider")
	}
	allocs := testing.AllocsPerRun(200, func() {
		CanonicalView(body)
	})
	if allocs != 0 {
		t.Fatalf("CanonicalView no-divider allocations = %v, want 0", allocs)
	}
	stripped, ok := StripTranslationSuffix(body)
	if ok || stripped != body {
		t.Fatalf("no-divider passthrough broken: ok=%v", ok)
	}
}

func TestCanonicalBodyEqualIgnoresSuffixOnlyDeltas(t *testing.T) {
	original := "Agent: Coordinator\nType: SPEC\n## Requirement\n\nThe system MUST work.\n"
	if !CanonicalBodyEqual(original, suffixedBody(original, "Agent: Coordinator\n## Requirement\n")) {
		t.Fatal("suffix-only delta must compare equal")
	}
	if !CanonicalBodyEqual(original+"\n", original) {
		t.Fatal("trailing newline delta must compare equal")
	}
	if CanonicalBodyEqual(original, original+"\n\nHuman note after write.") {
		t.Fatal("canonical content change must compare unequal")
	}
}

func TestCanonicalTitleStripsTranslationSuffix(t *testing.T) {
	if got := CanonicalTitle("修复问题 || Fix the issue"); got != "修复问题" {
		t.Fatalf("CanonicalTitle = %q, want %q", got, "修复问题")
	}
	if got := CanonicalTitle("修复问题"); got != "修复问题" {
		t.Fatalf("CanonicalTitle = %q, want unchanged", got)
	}
	if got := CanonicalTitle("keep || inner || suffix"); got != "keep || inner" {
		t.Fatalf("CanonicalTitle = %q, want %q", got, "keep || inner")
	}
}

func TestTranslationDividerLine(t *testing.T) {
	body := "a\n\n" + testTranslationDivider + "\n\nb"
	if got := TranslationDividerLine(body); got != 2 {
		t.Fatalf("TranslationDividerLine = %d, want 2", got)
	}
	if got := TranslationDividerLine("a\nb"); got != -1 {
		t.Fatalf("TranslationDividerLine = %d, want -1", got)
	}
	two := "a\n" + testTranslationDivider + "\n" + testTranslationDivider
	if got := TranslationDividerLine(two); got != -1 {
		t.Fatalf("TranslationDividerLine with two dividers = %d, want -1", got)
	}
}
