package issues

import (
	"strings"
	"testing"

	"github.com/higress-group/issue-spec/internal/server/models"
)

const contributionTranslationDivider = "<!--This is a translation content dividing line, the content below is generated by machine, please do not modify the content below-->"

func TestCanonicalProposalContributionToleratesTranslatedBodies(t *testing.T) {
	original := "<!-- issue-spec:issue=proposal change=contribution version=1 -->\n# Proposal\n\nBody.\n"
	translated := original + "\n\n" + contributionTranslationDivider + "\n\n" + strings.ToUpper(original)
	input := models.NewIssue{Title: "proposal", Body: translated, Labels: []string{"issue-spec/proposal"}}
	if !canonicalProposalContribution(input) {
		t.Fatal("translated canonical proposal contribution was rejected")
	}
	degraded := original + "\n\n" + contributionTranslationDivider + "\n\n<!--issue-spec:issue=proposal change=contribution version=1-->\n"
	if !canonicalProposalContribution(models.NewIssue{Title: "proposal", Body: degraded, Labels: []string{"issue-spec/proposal"}}) {
		t.Fatal("degraded marker copy in suffix was rejected")
	}
	duplicated := original + "<!-- issue-spec:issue=proposal change=other version=1 -->\n"
	if canonicalProposalContribution(models.NewIssue{Title: "proposal", Body: duplicated, Labels: []string{"issue-spec/proposal"}}) {
		t.Fatal("genuine duplicate marker must still be rejected")
	}
}
