package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io/fs"
	"mime"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 3 {
		fatal("usage: generate WEB_DIST STATICUI_DIR")
	}
	source, destination := os.Args[1], os.Args[2]
	if err := syncTree(source, filepath.Join(destination, "dist")); err != nil {
		fatal(err.Error())
	}
	if err := writeManifest(filepath.Join(destination, "dist"), filepath.Join(destination, "manifest_gen.go")); err != nil {
		fatal(err.Error())
	}
}

func syncTree(source, destination string) error {
	temporary := destination + ".tmp"
	_ = os.RemoveAll(temporary)
	if err := os.MkdirAll(temporary, 0o755); err != nil {
		return err
	}
	if err := filepath.WalkDir(source, func(name string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		relative, err := filepath.Rel(source, name)
		if err != nil || relative == "." {
			return err
		}
		target := filepath.Join(temporary, relative)
		if entry.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		if entry.Type()&os.ModeSymlink != 0 || !entry.Type().IsRegular() {
			return fmt.Errorf("unsupported web asset %s", relative)
		}
		content, err := os.ReadFile(name)
		if err != nil {
			return err
		}
		content = normalizeText(relative, content)
		return os.WriteFile(target, content, 0o644)
	}); err != nil {
		_ = os.RemoveAll(temporary)
		return err
	}
	_ = os.RemoveAll(destination + ".old")
	if err := os.Rename(destination, destination+".old"); err != nil && !os.IsNotExist(err) {
		return err
	}
	if err := os.Rename(temporary, destination); err != nil {
		_ = os.Rename(destination+".old", destination)
		return err
	}
	return os.RemoveAll(destination + ".old")
}

func normalizeText(name string, content []byte) []byte {
	switch strings.ToLower(filepath.Ext(name)) {
	case ".css", ".html", ".js", ".json", ".map", ".svg":
	default:
		return content
	}
	lines := strings.Split(string(content), "\n")
	for index := range lines {
		lines[index] = strings.TrimRight(lines[index], " \t")
	}
	return []byte(strings.Join(lines, "\n"))
}

func writeManifest(root, destination string) error {
	var names []string
	if err := filepath.WalkDir(root, func(name string, entry fs.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}
		relative, err := filepath.Rel(root, name)
		if err != nil {
			return err
		}
		names = append(names, filepath.ToSlash(relative))
		return nil
	}); err != nil {
		return err
	}
	sort.Strings(names)
	var output strings.Builder
	output.WriteString("// Code generated by staticui/cmd/generate; DO NOT EDIT.\n\npackage staticui\n\nfunc init() {\n\tmanifest = map[string]Asset{\n")
	for _, name := range names {
		content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)))
		if err != nil {
			return err
		}
		digest := sha256.Sum256(content)
		contentType := mime.TypeByExtension(filepath.Ext(name))
		if contentType == "" {
			contentType = "application/octet-stream"
		}
		immutable := name != "index.html" && name != ".vite/manifest.json" && strings.HasPrefix(name, "assets/")
		fmt.Fprintf(&output, "\t\t%s: {ContentType: %s, SHA256: %s, Immutable: %t},\n",
			strconv.Quote(name), strconv.Quote(contentType), strconv.Quote(hex.EncodeToString(digest[:])), immutable)
	}
	output.WriteString("\t}\n}\n")
	temporary := destination + ".tmp"
	if err := os.WriteFile(temporary, []byte(output.String()), 0o644); err != nil {
		return err
	}
	return os.Rename(temporary, destination)
}

func fatal(message string) {
	fmt.Fprintln(os.Stderr, "generate static ui:", message)
	os.Exit(1)
}
