package reconcile

import (
	"strings"
	"testing"

	"github.com/higress-group/issue-spec/internal/model"
)

const engineTranslationDivider = "<!--This is a translation content dividing line, the content below is generated by machine, please do not modify the content below-->"

func appendBotSuffix(body, extra string) string {
	suffix := body + "\n\n" + engineTranslationDivider + "\n\n" + strings.ToUpper(body)
	if extra != "" {
		suffix += "\n\n" + extra
	}
	return suffix
}

// botSuffixAfterWrite simulates the translation bot appending its suffix to the
// stored body between issue-spec's own successful write and re-observation.
func botSuffixAfterWrite(extra string) func(*fakeBackend, int, int) {
	applied := false
	return func(f *fakeBackend, issue int, _ int) {
		if applied || issue != 3 || f.writes == 0 {
			return
		}
		applied = true
		f.comments[3][0].Body = appendBotSuffix(f.comments[3][0].Body, extra)
	}
}

func TestReconcileToleratesBotSuffixAfterStrictConditionalWrite(t *testing.T) {
	f := newFake()
	before := typedBody(t, "TASK", "TASK-001", "confirmed")
	addComment(f, 3, 2, before)
	f.listHook = botSuffixAfterWrite("")
	plan := Plan{Version: 1, Repo: "o/r", Operations: []Operation{{ID: "transition", Kind: "transition",
		Target: Target{Issue: 3, Type: "TASK", ID: "TASK-001"}, Desired: Desired{Status: "done"},
		Precondition: Precondition{RepresentationVersion: 1}}}}

	result, err := (Engine{Backend: f}).Run(t.Context(), plan, "")
	if err != nil {
		t.Fatal(err)
	}
	if !result.OK || result.Updated != 1 || result.Conflicted != 0 {
		t.Fatalf("result=%+v", result)
	}
	operation := result.Operations[0]
	if operation.Status != "updated" || operation.Message != "" {
		t.Fatalf("operation=%+v", operation)
	}
	if operation.BeforeDigest == operation.AfterDigest {
		t.Fatal("transition digests must differ across the status change")
	}
	if !strings.Contains(f.comments[3][0].Body, engineTranslationDivider) {
		t.Fatal("provider body with suffix was rewritten")
	}
	if operation.AfterDigest != model.RepresentationDigest(f.comments[3][0].Body) {
		t.Fatal("after digest must match the suffixed observed body")
	}
}

func TestReconcileStillConflictsOnCanonicalDriftAfterWrite(t *testing.T) {
	f := newFake()
	before := typedBody(t, "TASK", "TASK-001", "confirmed")
	addComment(f, 3, 2, before)
	var written string
	applied := false
	f.listHook = func(backend *fakeBackend, issue int, _ int) {
		if applied || issue != 3 || backend.writes == 0 {
			return
		}
		applied = true
		written = backend.comments[3][0].Body
		drifted := strings.Replace(written, "content", "concurrently edited content", 1)
		backend.comments[3][0].Body = appendBotSuffix(drifted, "")
	}
	plan := Plan{Version: 1, Repo: "o/r", Operations: []Operation{{ID: "transition", Kind: "transition",
		Target: Target{Issue: 3, Type: "TASK", ID: "TASK-001"}, Desired: Desired{Status: "done"},
		Precondition: Precondition{RepresentationVersion: 1}}}}

	result, err := (Engine{Backend: f}).Run(t.Context(), plan, "")
	if err != nil {
		t.Fatal(err)
	}
	if result.Conflicted != 1 || f.writes != 1 {
		t.Fatalf("result=%+v writes=%d", result, f.writes)
	}
	operation := result.Operations[0]
	if operation.Status != "conflicted" || !strings.Contains(operation.Message, "canonical representation digest did not match") {
		t.Fatalf("operation=%+v", operation)
	}
	if strings.Contains(operation.Message, "exact representation digest") {
		t.Fatalf("message claims byte exactness: %q", operation.Message)
	}
	if !strings.Contains(operation.Message, model.RepresentationDigest(written)) {
		t.Fatalf("message omits the written canonical digest: %q", operation.Message)
	}
	if model.RepresentationDigest(written) == model.RepresentationDigest(f.comments[3][0].Body) {
		t.Fatal("canonical drift must produce differing digests in the mismatch message")
	}
}

func TestReconcileToleratesBotSuffixAfterNonAtomicWrite(t *testing.T) {
	f := newFake()
	before := typedBody(t, "TASK", "TASK-001", "confirmed")
	addComment(f, 3, 2, before)
	f.versions[2] = 0
	f.listHook = botSuffixAfterWrite("")
	plan := Plan{Version: 1, Repo: "o/r", AllowNonAtomic: true, Operations: []Operation{{ID: "transition", Kind: "transition",
		Target: Target{Issue: 3, Type: "TASK", ID: "TASK-001"}, Desired: Desired{Status: "done"},
		Precondition: Precondition{BodyDigest: model.RepresentationDigest(before)}}}}

	result, err := (Engine{Backend: f}).Run(t.Context(), plan, "")
	if err != nil {
		t.Fatal(err)
	}
	if !result.OK || result.Updated != 1 || result.Conflicted != 0 {
		t.Fatalf("result=%+v", result)
	}
	if got := result.Operations[0].Status; got != "updated" {
		t.Fatalf("operation status=%s", got)
	}
}
