package jobs

import (
	"context"
	"sort"
	"testing"
	"time"

	"github.com/higress-group/issue-spec/internal/commentrunner/state"
	"github.com/higress-group/issue-spec/internal/github"
	"github.com/higress-group/issue-spec/internal/model"
)

const jobsTranslationDivider = "<!--This is a translation content dividing line, the content below is generated by machine, please do not modify the content below-->"

func withBotSuffix(body string) string {
	return body + "\n\n" + jobsTranslationDivider + "\n\n" + body
}

func TestIssueSpecArtifactProviderToleratesTranslatedQuestionAndAnswer(t *testing.T) {
	questionURL := "https://github.com/o/r/issues/30#issuecomment-3001"
	questionBody := choiceQuestionBody(t, "QUESTION-001")
	snapshot, err := model.SnapshotQuestion(questionBody, questionURL)
	if err != nil {
		t.Fatal(err)
	}
	answer := answerBody(t, "ANSWER-001", snapshot, "old")
	base := time.Date(2026, time.August, 16, 9, 0, 0, 0, time.UTC)
	actor := &github.User{Login: "reviewer"}
	backend := &artifactBackend{
		issues: map[int]github.Issue{
			30: {Number: 30, HTMLURL: "https://github.com/o/r/issues/30", URL: "https://api.github.com/repos/o/r/issues/30", Title: "implement", State: "open"},
		},
		comments: map[int][]github.Comment{
			30: {
				{ID: 3001, HTMLURL: questionURL, URL: "https://api.github.com/repos/o/r/issues/comments/3001", IssueNumber: 30, Body: withBotSuffix(questionBody)},
				{ID: 3010, HTMLURL: "https://github.com/o/r/issues/30#issuecomment-3010", IssueNumber: 30, Body: withBotSuffix(answer), User: actor, CreatedAt: base, UpdatedAt: base},
			},
		},
	}

	artifacts, err := (&IssueSpecArtifactProvider{GitHub: backend}).ArtifactsForJob(
		context.Background(), state.Job{Repo: "o/r", IssueNumber: 30},
	)
	if err != nil {
		t.Fatal(err)
	}
	var ids []string
	for _, artifact := range artifacts {
		ids = append(ids, artifact.Comment.ID)
	}
	sort.Strings(ids)
	want := []string{"ANSWER-001", "ISSUE-030", "QUESTION-001"}
	for _, id := range want {
		found := false
		for _, got := range ids {
			if got == id {
				found = true
			}
		}
		if !found {
			t.Fatalf("artifact ids = %v, want %v among them", ids, want)
		}
	}
}
