// Code generated by staticui/cmd/generate; DO NOT EDIT.

package staticui

func init() {
	manifest = map[string]Asset{
		".vite/manifest.json":                    {ContentType: "application/json", SHA256: "d3123ee1da5d3312a7aafd214f490f404a2c40c0eb714d0221d0c10e836427aa", Immutable: false},
		"assets/board-page-C-sKXWMc.js":          {ContentType: "text/javascript; charset=utf-8", SHA256: "4b9459b007d5498af462dad408ff426a25838e584b56a8a60659dc44772d1aaa", Immutable: true},
		"assets/create-page-B1R--z-h.js":         {ContentType: "text/javascript; charset=utf-8", SHA256: "2564befc9e09ef098e91c74813b77310191ed21394a75203de4f3c3a088fa133", Immutable: true},
		"assets/detail-page-BkVKKMmE.css":        {ContentType: "text/css; charset=utf-8", SHA256: "7c28931d34a683f50e7a4bd5f4d1e014eebe8931f81d8eec54a6e38b429d5b11", Immutable: true},
		"assets/detail-page-CCUllGzu.js":         {ContentType: "text/javascript; charset=utf-8", SHA256: "5db2c7c1469674a85f79847d64d8f78d866d9b66078037c951be0e3eb0dfbc2c", Immutable: true},
		"assets/detail-page-D6DTefic.js":         {ContentType: "text/javascript; charset=utf-8", SHA256: "0565349579935ab869cc3464285ea043cd0efb90a4861f451f873295c407ad21", Immutable: true},
		"assets/index-CADVd-RL.js":               {ContentType: "text/javascript; charset=utf-8", SHA256: "bf765b4faf935238d585742544930d8af2fd89eb2d49c913af379c38694fcf03", Immutable: true},
		"assets/index-CSagopqF.css":              {ContentType: "text/css; charset=utf-8", SHA256: "34fb259ed5f03cb113b5f9283c93741de28497526e8801007d9e5dddd4767ff5", Immutable: true},
		"assets/issue-editor-CdnBa9Ix.css":       {ContentType: "text/css; charset=utf-8", SHA256: "0c14176e9384da786c8e23a779b7e6a4afbe360da2012bcff3f60656f3fbbdb4", Immutable: true},
		"assets/issue-editor-DYRjArNQ.js":        {ContentType: "text/javascript; charset=utf-8", SHA256: "60eeb338e2f853fb5b4d3fd8b206658f2e37ad4626ec5c727daf7a9c09608fa3", Immutable: true},
		"assets/label-chips-D-LX0cRZ.js":         {ContentType: "text/javascript; charset=utf-8", SHA256: "7d4dda022e11abe85876882be2bb929ca000554b273f5f2206ea98c4933298ad", Immutable: true},
		"assets/label-chips-DMPnSd3b.css":        {ContentType: "text/css; charset=utf-8", SHA256: "99c2191e3068801db61c6c13195f963b0318404cdcf26c258d56713cafde351e", Immutable: true},
		"assets/list-page-CLpJBlnT.js":           {ContentType: "text/javascript; charset=utf-8", SHA256: "21458ed3fac93f96e2a609404502adc55798840ec300d187f9f5d03b1facae07", Immutable: true},
		"assets/message-square-text-DJbl93tV.js": {ContentType: "text/javascript; charset=utf-8", SHA256: "5e06cb45d609d628aeb192a8ab292acb2e6a7a150ebee1226b3010f928ddd0fb", Immutable: true},
		"assets/relationships-2US2tFkG.js":       {ContentType: "text/javascript; charset=utf-8", SHA256: "e806433e346e85492b09cc09807182b7a9059683b5becf4b1d9f3a95bed84e50", Immutable: true},
		"assets/relationships-BcELNV6j.css":      {ContentType: "text/css; charset=utf-8", SHA256: "0015b0a168fdba19abf0a6a1e33cbbd7844e522dd2f70775472476157fe15237", Immutable: true},
		"assets/relationships-Bu2h6EZH.js":       {ContentType: "text/javascript; charset=utf-8", SHA256: "a10df18fedd5f7cef824053586aa6195b1bffe6873718d642f1ec58e00de1abb", Immutable: true},
		"assets/repository-context-CTrLlgtY.js":  {ContentType: "text/javascript; charset=utf-8", SHA256: "939de4ee587ecb236773bdf3b9ddab223144b97d7d140362583203eed4757678", Immutable: true},
		"assets/rotate-ccw-B9yIrCp9.js":          {ContentType: "text/javascript; charset=utf-8", SHA256: "ff1446cc0967782c597f6bbfad078fd65f35c58c35f8673335e9f4a45806bd49", Immutable: true},
		"assets/search-page-ClMxaFmR.js":         {ContentType: "text/javascript; charset=utf-8", SHA256: "08334165bbfca707368ad0494d1a3eaf89fde60f9c7d2862e90ba6115971cbfc", Immutable: true},
		"assets/session-0AyzV_oc.js":             {ContentType: "text/javascript; charset=utf-8", SHA256: "7e3650b9e01bdedbd3a84f262ce91071bee7bd542dac5d7c89a86c2e4bb839a8", Immutable: true},
		"assets/workspace-page-BpMqzTnh.js":      {ContentType: "text/javascript; charset=utf-8", SHA256: "0ed751480bc5a14d93b20830b3f4a02e27ac67de11ec9104683834d14fb6b0d4", Immutable: true},
		"index.html":                             {ContentType: "text/html; charset=utf-8", SHA256: "542f61c252400d259609faa79890cbeda17a5d0982fe6f6d771edde487208c4e", Immutable: false},
	}
}
