// Code generated by staticui/cmd/generate; DO NOT EDIT.

package staticui

func init() {
	manifest = map[string]Asset{
		".vite/manifest.json":                   {ContentType: "application/json", SHA256: "b8605a85bef163ecf935fd506a0f2a52bef2be657b324869d6d20a0ea14b5e86", Immutable: false},
		"assets/board-page-D8YAeEc4.js":         {ContentType: "text/javascript; charset=utf-8", SHA256: "77113a8ff29d75ad2cc8dd71590b101d2cc2d09c7f5b9a38006a97bacebf99c4", Immutable: true},
		"assets/create-page-CvJ6cSbN.js":        {ContentType: "text/javascript; charset=utf-8", SHA256: "a0b25541cbee63a847cf8da50aa16b5a12a08c4a76a7afb840423836a2efd7d1", Immutable: true},
		"assets/detail-page-BkVKKMmE.css":       {ContentType: "text/css; charset=utf-8", SHA256: "7c28931d34a683f50e7a4bd5f4d1e014eebe8931f81d8eec54a6e38b429d5b11", Immutable: true},
		"assets/detail-page-DLe3H0DO.js":        {ContentType: "text/javascript; charset=utf-8", SHA256: "26d22b7bcb240538905afe1864a6307a36c462815eae07d78e572f2975b54f15", Immutable: true},
		"assets/detail-page-oMY-_blt.js":        {ContentType: "text/javascript; charset=utf-8", SHA256: "de181d491ada9ede901dd493a10d74a3f5a5b34a94ed3b01b6e50520cc261b0e", Immutable: true},
		"assets/index-1PkdqHUq.css":             {ContentType: "text/css; charset=utf-8", SHA256: "cb17efeef83e1b99a237eca426709fdbace006ebf276d16242c14e6875bfe0b7", Immutable: true},
		"assets/index-CWlnASif.js":              {ContentType: "text/javascript; charset=utf-8", SHA256: "8feb0b8651ce8f794670a2d57feafe90ebc595813072382aa9962116929c594f", Immutable: true},
		"assets/issue-editor-B6z4B1Gz.js":       {ContentType: "text/javascript; charset=utf-8", SHA256: "d8bcf9328c46c81bed954459e8bae55964a3882887db4950213caf25a8cea309", Immutable: true},
		"assets/issue-editor-CdnBa9Ix.css":      {ContentType: "text/css; charset=utf-8", SHA256: "0c14176e9384da786c8e23a779b7e6a4afbe360da2012bcff3f60656f3fbbdb4", Immutable: true},
		"assets/label-chips-DMPnSd3b.css":       {ContentType: "text/css; charset=utf-8", SHA256: "99c2191e3068801db61c6c13195f963b0318404cdcf26c258d56713cafde351e", Immutable: true},
		"assets/label-chips-DvhvesY3.js":        {ContentType: "text/javascript; charset=utf-8", SHA256: "8b943151b7ecd184217022744046db2708f9b3c0104f7254ebfe4105d2ec11a7", Immutable: true},
		"assets/list-page-BeixAK4_.js":          {ContentType: "text/javascript; charset=utf-8", SHA256: "59325c38d3f979d7f30e5a2eba9106585dabc71c252db59dcd4a4677a9bf4034", Immutable: true},
		"assets/lock-keyhole-DLPI7Yeh.js":       {ContentType: "text/javascript; charset=utf-8", SHA256: "9381aaa56931e95fda283b84154e00448dc24a706ce8c307ac94daee4aec6a67", Immutable: true},
		"assets/repository-context-1pV_uRYC.js": {ContentType: "text/javascript; charset=utf-8", SHA256: "4cfd61011cf1694dc3faad724a5942633e8b191cef36db41a7e69741e0c463de", Immutable: true},
		"assets/rotate-ccw-B7_3hFGa.js":         {ContentType: "text/javascript; charset=utf-8", SHA256: "6cc8cc5714373a8ba6cad786a3e6386c190f28e4d8346e9bd2d2661e568f76ff", Immutable: true},
		"assets/session-D1RC79Ii.js":            {ContentType: "text/javascript; charset=utf-8", SHA256: "924958524245b37f444a428b0d9f4a8e961578c5b440ebebeef5c57b3426a22d", Immutable: true},
		"assets/workspace-page-B7ur8Q5R.js":     {ContentType: "text/javascript; charset=utf-8", SHA256: "3dedef9929b778389648d0e8a7b39cfecf517aef86f293e706b582fd8b8d9c64", Immutable: true},
		"index.html":                            {ContentType: "text/html; charset=utf-8", SHA256: "483a51332a08fb6ee05cf61c53aed3a8d6ae6956d2a0357f9542365ca12cee8f", Immutable: false},
	}
}
