package staticui

type Asset struct {
	ContentType string
	SHA256      string
	Immutable   bool
}

// manifest is generated by cmd/generate from the pinned Vite production
// output. It is deliberately metadata-only; asset bytes remain normal files
// consumed by go:embed.
var manifest = map[string]Asset{}
