// Code generated by staticui/cmd/generate; DO NOT EDIT.

package staticui

func init() {
	manifest = map[string]Asset{
		".vite/manifest.json":                   {ContentType: "application/json", SHA256: "19923ee3fd94bfd9cc89bd3e6b155cc802817a6436115bd108b06a0fa38759e6", Immutable: false},
		"assets/board-page-B3_33ga6.js":         {ContentType: "text/javascript; charset=utf-8", SHA256: "15a2efb24ab3fbcbfb399919795b6fcf2fcc10ae5b267d2bd82d536ff68187d9", Immutable: true},
		"assets/create-page-1sxiWYrt.js":        {ContentType: "text/javascript; charset=utf-8", SHA256: "e0a627ad498f6152a98c19b425b8b06968cbbbe4cf2f57c057f91dca66f7cb8a", Immutable: true},
		"assets/detail-page-BkVKKMmE.css":       {ContentType: "text/css; charset=utf-8", SHA256: "7c28931d34a683f50e7a4bd5f4d1e014eebe8931f81d8eec54a6e38b429d5b11", Immutable: true},
		"assets/detail-page-Cr7i6rMh.js":        {ContentType: "text/javascript; charset=utf-8", SHA256: "d02b8f9f5e2c4d1acf5cafd6120f4c024fa8bc613cdd17f61b5358bc6578f476", Immutable: true},
		"assets/detail-page-D4Tj9_OT.js":        {ContentType: "text/javascript; charset=utf-8", SHA256: "4feeb7437747695abbc237407e4766f0927b27e28512ddfa9662bc2efbf88aae", Immutable: true},
		"assets/index-BiFutX6n.css":             {ContentType: "text/css; charset=utf-8", SHA256: "dc174ea9766ecaeea4a05ab7ccb30dec384e8c79f6428801b6c731fe84881590", Immutable: true},
		"assets/index-CCh8wtex.js":              {ContentType: "text/javascript; charset=utf-8", SHA256: "df9d455323852ab3cae3c0ad5b9f82e61913f3b965481d87a2ea1e53cf2a82ee", Immutable: true},
		"assets/issue-editor-CdnBa9Ix.css":      {ContentType: "text/css; charset=utf-8", SHA256: "0c14176e9384da786c8e23a779b7e6a4afbe360da2012bcff3f60656f3fbbdb4", Immutable: true},
		"assets/issue-editor-VDzwmhNF.js":       {ContentType: "text/javascript; charset=utf-8", SHA256: "c4154ead3f05f9fa02793eaf3ed1335eabbc211fa7d8519ca0a25eb5f8040d2c", Immutable: true},
		"assets/label-chips-BjYAOyLR.js":        {ContentType: "text/javascript; charset=utf-8", SHA256: "f0604449f23a2f32d89eb47342fcf3fa7f1f98c3b0407572d82eeff5add6865d", Immutable: true},
		"assets/label-chips-DMPnSd3b.css":       {ContentType: "text/css; charset=utf-8", SHA256: "99c2191e3068801db61c6c13195f963b0318404cdcf26c258d56713cafde351e", Immutable: true},
		"assets/list-page-nGcLD3xT.js":          {ContentType: "text/javascript; charset=utf-8", SHA256: "cca37b53dbf6539e3d61d34254b25ed462ecce91e9d9fcf753378a163a607cea", Immutable: true},
		"assets/lock-keyhole-CkamhGp3.js":       {ContentType: "text/javascript; charset=utf-8", SHA256: "866321246c1dc782e287f85aac753c77d64b73c815980bdb4d02ec2c07de584c", Immutable: true},
		"assets/repository-context-tqpy5cD5.js": {ContentType: "text/javascript; charset=utf-8", SHA256: "7b08a0a824213822c1afd7a5850b3b0ea36373012c2dfb57140a0fd792ac0c0c", Immutable: true},
		"assets/rotate-ccw-DRbOHbjO.js":         {ContentType: "text/javascript; charset=utf-8", SHA256: "c45de15e6648859735f7edbb5d790466372119eba77f3ad2622351d83a29e92a", Immutable: true},
		"assets/session-DVTsIWKS.js":            {ContentType: "text/javascript; charset=utf-8", SHA256: "367ab71cb8b15fc2355baa1181fe4aa45823a3241f7004fad60eec10aa7ae67f", Immutable: true},
		"assets/workspace-page-DINzkqX5.js":     {ContentType: "text/javascript; charset=utf-8", SHA256: "616ec22141256a0ee8787fbe6944a93b11b1bd308192fd6d1e981dec4f3e8459", Immutable: true},
		"index.html":                            {ContentType: "text/html; charset=utf-8", SHA256: "c0673dd1a2d63f5c43302979e5725dc4aca4af3e380e02ca170929d3c724df4d", Immutable: false},
	}
}
